investor:
  mobile_phone: '15880531746'
  pwd: '12345678'
  reg_name: investor
  type: 1
borrower:
  mobile_phone: '15875382609'
  pwd: '12345678'
  reg_name: borrower
  type: 1
admin:
  mobile_phone: '15889713056'
  pwd: '12345678'
  reg_name: admin
  type: 0
